// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineMovieStore.Data;

#nullable disable

namespace OnlineMovieStore.Data.Migrations
{
    [DbContext(typeof(OnlineMovieStoreDbContext))]
    partial class OnlineMovieStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineMovieStore.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPopular = true,
                            Name = "Richard Tiffany Gere",
                            ShortDescription = "Richard Tiffany Gere is an American actor. He began in films in the 1970s, playing a supporting role in Looking for Mr. Goodbar and a starring role in Days of Heaven. He came to prominence with his role in the film American Gigolo, which established him as a leading man and a sex symbol."
                        },
                        new
                        {
                            Id = 2,
                            IsPopular = true,
                            Name = "Thomas Cruise",
                            ShortDescription = "Thomas Cruise Mapother IV is an American actor, producer and pilot. One of the world's highest-paid actors, he has received various accolades, including an Honorary Palme d'Or and three Golden Globe Awards, in addition to nominations for four Academy Awards."
                        },
                        new
                        {
                            Id = 3,
                            IsPopular = true,
                            Name = "Morgan Freeman",
                            ShortDescription = "Morgan Freeman is an American actor, producer, and narrator. He is known for his distinctive deep voice and various roles in a wide variety of film genres"
                        },
                        new
                        {
                            Id = 4,
                            IsPopular = true,
                            Name = "Alfredo James Pacino",
                            ShortDescription = "Alfredo James Pacino is an American actor. Considered one of the greatest and most influential actors of the 20th century, Pacino has received numerous accolades: including an Academy Award"
                        },
                        new
                        {
                            Id = 5,
                            IsPopular = true,
                            Name = "Christian Charles Philip Bale",
                            ShortDescription = "Christian Charles Philip Bale is an English actor. Known for his versatility and physical transformations for his roles, he has been a leading man in films of several genres. He has received various accolades, including an Academy Award and two Golden Globe Awards."
                        },
                        new
                        {
                            Id = 6,
                            IsPopular = false,
                            Name = "James Eugene Carrey",
                            ShortDescription = "James Eugene Carrey is a Canadian and American actor and comedian. Known for his energetic slapstick performances, Carrey first gained recognition in 1990, after landing a role in the American sketch comedy television series In Living Color."
                        },
                        new
                        {
                            Id = 7,
                            IsPopular = false,
                            Name = "Ryan Thomas Gosling",
                            ShortDescription = "Ryan Thomas Gosling is a Canadian actor. Prominent in both independent film and major studio features of varying genres, his films have accrued a worldwide box office gross of over 1.9 billion USD."
                        },
                        new
                        {
                            Id = 8,
                            IsPopular = false,
                            Name = "Robbie Robertson",
                            ShortDescription = "Jaime Royal \"Robbie\" Robertson OC was a Canadian musician. He was lead guitarist for Bob Dylan in the mid-late 1960s and early-mid 1970s, guitarist and songwriter with the Band from their inception until 1978, and a solo artist. Robertson's work with the Band was instrumental in creating the Americana music genre."
                        },
                        new
                        {
                            Id = 9,
                            IsPopular = false,
                            Name = "Bill Istvan Günther Skarsgård",
                            ShortDescription = "Bill Istvan Günther Skarsgård is a Swedish actor. He is best known for portraying Pennywise in the horror films It and It Chapter Two, based on Stephen King's novel of the same name. Other horror appearances were in the film Barbarian and the series Hemlock Grove and Castle Rock."
                        },
                        new
                        {
                            Id = 10,
                            IsPopular = false,
                            Name = "Noah Leslie Hathaway",
                            ShortDescription = "Noah Leslie Hathaway is an American actor and a former teen idol. He is best known for his roles as Atreyu in the 1984 film The NeverEnding Story and for portraying Boxey on the original television series Battlestar Galactica. His work in The NeverEnding Story made him particularly popular as a teen idol in Europe"
                        });
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.BookmarkMovie", b =>
                {
                    b.Property<int>("BookmarkMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookmarkMovieId"));

                    b.Property<string>("WatchLater")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookmarkMovieId");

                    b.ToTable("BookmarkMovies");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Language", b =>
                {
                    b.Property<int>("LanguageMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageMovieId"));

                    b.Property<string>("LanguageMovieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageMovieId");

                    b.ToTable("webLanguages");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Login", b =>
                {
                    b.Property<int>("LoginMovieId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginMovieId"));

                    b.Property<string>("LoginUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginMovieId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryMovieId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("MovePart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieActors")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MovieCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MovieDescription")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieDirector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MovieLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MovieLength")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MovieProducer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MovieRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovieYearOfRelease")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SoldSubscriptions")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("ActorId");

                    b.HasIndex("CategoryMovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryMovieId = 0,
                            IsPopular = true,
                            MovieCountry = "Japan",
                            MovieDescription = "Synopsis. This heartwarming true story is an American adaptation of a Japanese tale about a loyal dog named Hachiko. This very special friend would accompany his master to the train station every day and return each afternoon to greet him after work.",
                            MovieDirector = "Lasse Hallström",
                            MovieLength = 0,
                            MovieName = "Hachiko",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryMovieId = 0,
                            IsPopular = true,
                            MovieCountry = "USA",
                            MovieDescription = "An American agent, under false suspicion of disloyalty, must discover and expose the real spy without the help of his organization. Ethan Hunt (Tom Cruise) and his I.M.F. team go undercover to bring down the N.O.C. list, a list of every Agent and spy in the I.M.F.",
                            MovieDirector = "Tom Cruise",
                            MovieLength = 0,
                            MovieName = "Mission Impossible",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryMovieId = 0,
                            IsPopular = true,
                            MovieCountry = "USA",
                            MovieDescription = "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
                            MovieDirector = "Frank Darabont",
                            MovieLength = 0,
                            MovieName = "The Shawshank Redemption",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryMovieId = 0,
                            IsPopular = true,
                            MovieCountry = "USA",
                            MovieDescription = "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
                            MovieDirector = "Francis Ford Coppola",
                            MovieLength = 0,
                            MovieName = "The Godfather",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryMovieId = 0,
                            IsPopular = false,
                            MovieCountry = "USA",
                            MovieDescription = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            MovieDirector = "Christopher Nolan",
                            MovieLength = 0,
                            MovieName = "The Dark Knight",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryMovieId = 0,
                            IsPopular = false,
                            MovieCountry = "USA",
                            MovieDescription = "Imbecilic best friends Lloyd Christmas (Jim Carrey) and Harry Dunne (Jeff Daniels) stumble across a suitcase full of money left behind in Harry's car by Mary Swanson (Lauren Holly), who was on her way to the airport. The pair decide to go to Aspen, Colo., to return the money, unaware that it is connected to a kidnapping. As Harry and Lloyd -- who has fallen in love with Mary -- are pursued across the country by hired killers and police, they find both their friendship and their brains tested.",
                            MovieDirector = "Peter Farrelly",
                            MovieLength = 0,
                            MovieName = "Dumb and dumber",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryMovieId = 0,
                            IsPopular = false,
                            MovieCountry = "USA",
                            MovieDescription = "In 1940s South Carolina, mill worker Noah Calhoun (Ryan Gosling) and rich girl Allie (Rachel McAdams) are desperately in love. But her parents don't approve. When Noah goes off to serve in World War II, it seems to mark the end of their love affair. In the interim, Allie becomes involved with another man (James Marsden). But when Noah returns to their small town years later, on the cusp of Allie's marriage, it soon becomes clear that their romance is anything but over.",
                            MovieDirector = "Nick Cassavetes",
                            MovieLength = 0,
                            MovieName = "The Notebook",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryMovieId = 0,
                            IsPopular = true,
                            MovieCountry = "USA",
                            MovieDescription = "Seventeen years after joining forces as the backing band for rockabilly cult hero Ronnie Hawkins, Canadian roots rockers The Band call it quits with a lavish farewell show at San Francisco's Winterland Ballroom on Nov. 25, 1976. Filmed by Martin Scorsese, this documentary features standout performances by rock legends such as Bob Dylan, Van Morrison, Eric Clapton, Joni Mitchell and Muddy Waters, as well as interviews tracing the group's history and discussing road life.",
                            MovieDirector = "Martin Scorsese",
                            MovieLength = 0,
                            MovieName = "The Last Waltz",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryMovieId = 0,
                            IsPopular = false,
                            MovieCountry = "USA",
                            MovieDescription = "A young woman discovers the rental home she booked is already occupied by a stranger. Against her better judgment, she decides to spend the night but soon discovers there's a lot more to fear than just an unexpected house guest.",
                            MovieDirector = "Zach Cregger",
                            MovieLength = 0,
                            MovieName = "Barbarian",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryMovieId = 0,
                            IsPopular = false,
                            MovieCountry = "USA",
                            MovieDescription = "On his way to school, Bastian (Barret Oliver) ducks into a bookstore to avoid bullies. Sneaking away with a book called The Neverending Story, Bastian begins reading it in the school attic. The novel is about Fantasia, a fantasy land threatened by The Nothing, a darkness that destroys everything it touches. The kingdom needs the help of a human child to survive. When Bastian reads a description of himself in the book, he begins to wonder if Fantasia is real and needs him to survive.",
                            MovieDirector = "Wolfgang Petersen",
                            MovieLength = 0,
                            MovieName = "TheNeverEnding Story",
                            MovieRating = 0,
                            MovieYearOfRelease = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0.0,
                            SoldSubscriptions = 0
                        });
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Genre")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("LastUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            MovieName = "Fiction"
                        },
                        new
                        {
                            MovieId = 2,
                            MovieName = "Action"
                        },
                        new
                        {
                            MovieId = 3,
                            MovieName = "Crime"
                        },
                        new
                        {
                            MovieId = 4,
                            MovieName = "Adventure"
                        },
                        new
                        {
                            MovieId = 5,
                            MovieName = "Drama"
                        },
                        new
                        {
                            MovieId = 6,
                            MovieName = "Fantasy"
                        },
                        new
                        {
                            MovieId = 7,
                            MovieName = "Thrillers"
                        },
                        new
                        {
                            MovieId = 8,
                            MovieName = "General"
                        },
                        new
                        {
                            MovieId = 9,
                            MovieName = "Horror"
                        },
                        new
                        {
                            MovieId = 10,
                            MovieName = "Uncategorised"
                        });
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.MovieSearch", b =>
                {
                    b.Property<int>("SearchMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchMovieId"));

                    b.Property<string>("MovieGenre")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("MovieIsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("MovieMovieName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SearchMovieId");

                    b.ToTable("MovieSearches");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.PhotoMovie", b =>
                {
                    b.Property<int>("PhotoMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoMovieId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(650)
                        .HasColumnType("nvarchar(650)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PhotoMovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("PhotoMovies");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Producer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Richard Gere"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tom Cruise"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Niki Marvin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Francis Ford Coppola"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Peter Farrelly"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mark Johnson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Garth Hudson"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Roy Lee"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bernd Eichinger"
                        });
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Shows", b =>
                {
                    b.Property<int>("ShowMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowMovieId"));

                    b.Property<string>("ShowDescription")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShowMovieName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ShowType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ShowMovieId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SoldSubscriptions")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.User", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(650)
                        .HasColumnType("nvarchar(650)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserAdress")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("UserAge")
                        .HasColumnType("int");

                    b.Property<string>("UserCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserCountry")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MovieId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("5fb79765-7acc-495c-84f9-33052e87cf53"),
                            Description = "****Admin User ****",
                            IsAdmin = true,
                            PasswordHash = new byte[] { 205, 180, 199, 254, 212, 49, 143, 84, 112, 247, 251, 226, 112, 44, 121, 223, 23, 8, 142, 15, 156, 244, 113, 84, 158, 52, 168, 64, 26, 164, 129, 95, 146, 9, 54, 15, 9, 179, 116, 165, 177, 200, 147, 7, 91, 0, 83, 43, 64, 145, 238, 221, 174, 213, 132, 85, 216, 24, 16, 41, 153, 198, 146, 189 },
                            PasswordSalt = new byte[] { 228, 10, 166, 123, 8, 238, 185, 189, 201, 214, 239, 67, 128, 3, 249, 137, 88, 230, 83, 122, 194, 63, 226, 84, 36, 95, 27, 114, 13, 107, 40, 107, 156, 25, 244, 192, 124, 175, 192, 58, 109, 77, 240, 198, 41, 23, 112, 233, 250, 176, 18, 43, 208, 135, 178, 148, 205, 135, 47, 23, 10, 183, 20, 3, 53, 21, 122, 35, 227, 82, 205, 80, 205, 195, 130, 151, 231, 48, 75, 171, 155, 15, 244, 74, 8, 223, 35, 104, 0, 16, 153, 240, 12, 150, 91, 242, 182, 225, 199, 218, 136, 62, 75, 74, 193, 16, 131, 161, 234, 43, 47, 184, 51, 144, 219, 14, 209, 77, 51, 77, 239, 239, 87, 8, 164, 3, 39, 220 },
                            Phone = "22332025",
                            UserAdress = "/",
                            UserAge = 0,
                            UserCity = "Skopje",
                            UserCountry = "Macedonia",
                            UserCreated = new DateTime(2023, 11, 7, 22, 10, 45, 523, DateTimeKind.Local).AddTicks(1159),
                            UserEmail = "smx.test@smx.com",
                            UserName = "onlineMoviestoreUsername"
                        });
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Movie", b =>
                {
                    b.HasOne("OnlineMovieStore.Entities.Actor", null)
                        .WithMany("Movies")
                        .HasForeignKey("ActorId");

                    b.HasOne("OnlineMovieStore.Entities.MovieCategory", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.PhotoMovie", b =>
                {
                    b.HasOne("OnlineMovieStore.Entities.Movie", null)
                        .WithMany("Photos")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Actor", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.Movie", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("OnlineMovieStore.Entities.MovieCategory", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
